FROM moussaabdenbi/inf1070:tp2-h2021

# Mettre à jour les paquets de l'image

# Installer elinks

# Copier le répertoire s

# Se placer dans le bon répertoire

# Compiler l'application

# Installer l'application

# Créer le répertoire /root/.config/s

